Enumerables: Rspec tests
PhillipUg/enumerable-methods pull request #4
Opened 2020-05-01 12:08 UTC by PhillipUg

## In this branch, we have done the following;
  - We have added tests for all our enumerable methods
  - We have changed project file structure and added lib and spec folders
  - Followed other project-specific guidelines as required by microverse

2020-05-02 00:54 UTC, majovanilla requested changes
Hey team, 👋

## You did a *great* job on this project! 💜 

- Your test coverage was excellent.

There are still some changes 👇 you need to implement to approve this request 🔍
- Some of your tests have typos, please take a look at them and correct them. 
- Check the comments below.


### Optional Changes:

If you want to make your project even better 🔥💥, I left a few suggestions you can implement. 
These are completely [Optional]: 🦔

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(new_array2).to eq([3, 4, 5, 6, 7])
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array1.my_each.to_a).to eq(array1)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

Your second expect is not related to the `it` statement you have. With just the first expect you would be checking for the enumerator, so you don't need it. Check that on all your other tests.

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array1.my_each_with_index.to_a).to eq(array1)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array1.my_select.to_a).to eq(array1)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_all? { |ele| ele.is_a?(Numeric) }).to be true
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_all? { |ele| ele < 3 }).to be false
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      end
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array1.my_all?(/e/)).to be false
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_any? { |ele| ele > 4 }).to be true
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_any? { |ele| ele > 5 }).to be false
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array2.my_any?(/o/)).to be true
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array2.my_any?(/s/)).to be false
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_none? { |ele| ele > 5 }).to be true
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_none? { |ele| ele > 4 }).to be false
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array2.my_none?(/s/)).to be true
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array2.my_none?(/o/)).to be false
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array1.my_count { |ele| ele > 2 }).to eq(2)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array4.count).to eq(4)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(range.my_map { 'cat' }).to eq(%w[cat cat cat cat cat])
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array1.my_map.to_a).to eq(array1)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +          expect(array2.my_inject { |acc, num| acc + num }).to eq('twothreetentwelve')
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +          expect(array1.my_inject(5) { |acc, num| acc * num }).to eq(120)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +          expect(array1.my_inject(:*)).to eq(24)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +          expect(array1.my_inject(5, :*)).to eq(120)
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      context 'if  atleast one of elements is not (false) or (nil)' do
**Optional**: try to keep your nesting simpler. If you write:
```
describe '#my_any?' do
    context 'when no block is given' do
        it 'should return true 'if at least one of elements is not (false) or (nil)'' do
          expect(array3.my_any?).to be true
        end
     end
// other context...
end
```
The code is more readable that way, and you only keep two contexts: `when block is given` and `when no block is given`.

Keep this in mind for all the other tests, if you decide to implement the change.

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +        expect(array2.my_select { |ele| ele.size > 3 }).to eq(%w[three twelve])
* [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      context 'if none of elements is (false) or (nil)' do
**Optional**: try to keep your nesting simpler. If you write:
```
describe '#my_all?' do
    context 'when no block is given' do
        it 'should return true 'if none of elements is (false) or (nil)'' do
          expect(array3.my_all?).to be true
        end
     end
// other context...
end
```
The code is more readable that way, and you only keep two contexts: `when block is given` and `when no block is given`.

Keep this in mind for all the other tests, if you decide to implement the change.

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      context 'if none of the elements is not (false) or (nil)' do
It should be: if none of the elements is (false) or (nil)

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      context 'if none of the elements is not (false) or (nil)' do
Check the optional change about nested contexts suggested above.

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      context 'when no initial value is specified' do
Check the optional change about nested contexts suggested above.

2020-05-02 00:54 UTC, majovanilla commented on spec/enumerables_spec.rb
> +      context 'when only symbol is specified as argument' do
Check the optional change about nested contexts suggested above.

2020-05-02 12:20 UTC, PhillipUg commented
Thanks @majovanilla for your detailed review :smile: . Let us implement the suggested changes and make another request

2020-05-02 12:29 UTC, PhillipUg commented
## We have corrected the following:
 - Implemented one expect statement for each 'it' block
 - resolved nesting complexity with the multiple 'context' blocks

2020-05-04 10:17 UTC, Torres-ssf approved these changes
### Project Approved :tada: :muscle: 
Hi there @PhillipUg :hand: 
Great job implementing the requested changes. Awesome job on this project :clap: 
**This PR approvoved**
Good luck with the next project

Happy coding :computer: 

**Sergio Torres**

2020-05-04 10:57 UTC, PhillipUg commented
Thanks @Torres-ssf :smile:

2020-05-04 10:57 UTC, merged